// scripts/set-env.js
// Writes src/environments/environment.prod.ts from environment variables at build time.
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

const API_URL =
  process.env.API_URL ||
  process.env.NGX_API_URL ||
  'https://m1p13mean-tendry-ricardo.onrender.com/api';
const STRIPE_KEY = process.env.STRIPE_PUBLIC_KEY || process.env.STRIPE_PK || '';

const content = `// This file was generated by set-env.js
const getApiUrl = () => {
  const host = typeof window !== 'undefined' ? window.location.hostname : 'localhost';
  const url = (host === 'localhost' || host === '127.0.0.1')
    ? 'http://localhost:3000/api'
    : '${API_URL}';
  return url.replace(/\\/+$/, '');
};

export const environment = {
  production: true,
  apiUrl: getApiUrl(),
  stripePublicKey: '${STRIPE_KEY}',
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('[set-env] Wrote', outPath);
