// scripts/set-env.js
const fs = require('fs');
const path = require('path');

// ============================================================
// URLs hardcodées - modifiez ici pour changer l'environnement
// ============================================================
const PROD_API_URL = 'https://m1p13mean-tendry-ricardo.onrender.com/api';
const PROD_STRIPE_KEY =
  'pk_test_51T6GHF9bqT14xCYZ0VMGADcVAnHEx0gUiyEv8pdeW3icSX5XggPdmTktkDTC0zA3MkuzjtQ5f9SPWQnMNtjTBJnz001W4Yh6PA';

// ============================================================
// Pour le dev local, lire le fichier .env (si présent)
// ============================================================
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });
const DEV_API_URL = process.env.API_URL || 'http://localhost:3000/api';
const DEV_STRIPE_KEY = process.env.STRIPE_PUBLIC_KEY || PROD_STRIPE_KEY;

const outPathProd = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
const outPathDev = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');

const prodContent = `// AUTO-GENERATED by set-env.js — DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  apiUrl: '${PROD_API_URL}',
  stripePublicKey: '${PROD_STRIPE_KEY}',
};
`;

const devContent = `// AUTO-GENERATED by set-env.js — DO NOT EDIT MANUALLY
// Pour changer l'URL en local, modifiez le fichier .env
export const environment = {
  production: false,
  apiUrl: '${DEV_API_URL}',
  stripePublicKey: '${DEV_STRIPE_KEY}',
};
`;

fs.mkdirSync(path.dirname(outPathProd), { recursive: true });

fs.writeFileSync(outPathProd, prodContent, { encoding: 'utf8' });
console.log('[set-env] PROD URL:', PROD_API_URL);
console.log('[set-env] Wrote', outPathProd);

fs.writeFileSync(outPathDev, devContent, { encoding: 'utf8' });
console.log('[set-env] DEV  URL:', DEV_API_URL);
console.log('[set-env] Wrote', outPathDev);
