// This file was generated by set-env.js
const getApiUrl = () => {
  const url = 'https://m1p13mean-tendry-ricardo.onrender.com/api';
  return url.replace(/\/+$/, '');
};

export const environment = {
  production: false,
  apiUrl: getApiUrl(),
  stripePublicKey: 'pk_test_51T6GHF9bqT14xCYZ0VMGADcVAnHEx0gUiyEv8pdeW3icSX5XggPdmTktkDTC0zA3MkuzjtQ5f9SPWQnMNtjTBJnz001W4Yh6PA',
};
